// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ClientSideTimestampsStatus string

const (
	ClientSideTimestampsStatus_ENABLED ClientSideTimestampsStatus = "ENABLED"
)

type EncryptionType string

const (
	EncryptionType_CUSTOMER_MANAGED_KMS_KEY EncryptionType = "CUSTOMER_MANAGED_KMS_KEY"
	EncryptionType_AWS_OWNED_KMS_KEY        EncryptionType = "AWS_OWNED_KMS_KEY"
)

type KeyspaceStatus_SDK string

const (
	KeyspaceStatus_SDK_ACTIVE   KeyspaceStatus_SDK = "ACTIVE"
	KeyspaceStatus_SDK_CREATING KeyspaceStatus_SDK = "CREATING"
	KeyspaceStatus_SDK_UPDATING KeyspaceStatus_SDK = "UPDATING"
	KeyspaceStatus_SDK_DELETING KeyspaceStatus_SDK = "DELETING"
)

type PointInTimeRecoveryStatus string

const (
	PointInTimeRecoveryStatus_ENABLED  PointInTimeRecoveryStatus = "ENABLED"
	PointInTimeRecoveryStatus_DISABLED PointInTimeRecoveryStatus = "DISABLED"
)

type Rs string

const (
	Rs_SINGLE_REGION Rs = "SINGLE_REGION"
	Rs_MULTI_REGION  Rs = "MULTI_REGION"
)

type SortOrder string

const (
	SortOrder_ASC  SortOrder = "ASC"
	SortOrder_DESC SortOrder = "DESC"
)

type TableStatus_SDK string

const (
	TableStatus_SDK_ACTIVE                              TableStatus_SDK = "ACTIVE"
	TableStatus_SDK_CREATING                            TableStatus_SDK = "CREATING"
	TableStatus_SDK_UPDATING                            TableStatus_SDK = "UPDATING"
	TableStatus_SDK_DELETING                            TableStatus_SDK = "DELETING"
	TableStatus_SDK_DELETED                             TableStatus_SDK = "DELETED"
	TableStatus_SDK_RESTORING                           TableStatus_SDK = "RESTORING"
	TableStatus_SDK_INACCESSIBLE_ENCRYPTION_CREDENTIALS TableStatus_SDK = "INACCESSIBLE_ENCRYPTION_CREDENTIALS"
)

type ThroughputMode string

const (
	ThroughputMode_PAY_PER_REQUEST ThroughputMode = "PAY_PER_REQUEST"
	ThroughputMode_PROVISIONED     ThroughputMode = "PROVISIONED"
)

type TimeToLiveStatus string

const (
	TimeToLiveStatus_ENABLED TimeToLiveStatus = "ENABLED"
)

type TypeStatus string

const (
	TypeStatus_ACTIVE    TypeStatus = "ACTIVE"
	TypeStatus_CREATING  TypeStatus = "CREATING"
	TypeStatus_DELETING  TypeStatus = "DELETING"
	TypeStatus_RESTORING TypeStatus = "RESTORING"
)
