//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingPolicy) DeepCopyInto(out *AutoScalingPolicy) {
	*out = *in
	if in.TargetTrackingScalingPolicyConfiguration != nil {
		in, out := &in.TargetTrackingScalingPolicyConfiguration, &out.TargetTrackingScalingPolicyConfiguration
		*out = new(TargetTrackingScalingPolicyConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingPolicy.
func (in *AutoScalingPolicy) DeepCopy() *AutoScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingSettings) DeepCopyInto(out *AutoScalingSettings) {
	*out = *in
	if in.AutoScalingDisabled != nil {
		in, out := &in.AutoScalingDisabled, &out.AutoScalingDisabled
		*out = new(bool)
		**out = **in
	}
	if in.MaximumUnits != nil {
		in, out := &in.MaximumUnits, &out.MaximumUnits
		*out = new(int64)
		**out = **in
	}
	if in.MinimumUnits != nil {
		in, out := &in.MinimumUnits, &out.MinimumUnits
		*out = new(int64)
		**out = **in
	}
	if in.ScalingPolicy != nil {
		in, out := &in.ScalingPolicy, &out.ScalingPolicy
		*out = new(AutoScalingPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingSettings.
func (in *AutoScalingSettings) DeepCopy() *AutoScalingSettings {
	if in == nil {
		return nil
	}
	out := new(AutoScalingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingSpecification) DeepCopyInto(out *AutoScalingSpecification) {
	*out = *in
	if in.ReadCapacityAutoScaling != nil {
		in, out := &in.ReadCapacityAutoScaling, &out.ReadCapacityAutoScaling
		*out = new(AutoScalingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.WriteCapacityAutoScaling != nil {
		in, out := &in.WriteCapacityAutoScaling, &out.WriteCapacityAutoScaling
		*out = new(AutoScalingSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingSpecification.
func (in *AutoScalingSpecification) DeepCopy() *AutoScalingSpecification {
	if in == nil {
		return nil
	}
	out := new(AutoScalingSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacitySpecification) DeepCopyInto(out *CapacitySpecification) {
	*out = *in
	if in.ReadCapacityUnits != nil {
		in, out := &in.ReadCapacityUnits, &out.ReadCapacityUnits
		*out = new(int64)
		**out = **in
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
	if in.WriteCapacityUnits != nil {
		in, out := &in.WriteCapacityUnits, &out.WriteCapacityUnits
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacitySpecification.
func (in *CapacitySpecification) DeepCopy() *CapacitySpecification {
	if in == nil {
		return nil
	}
	out := new(CapacitySpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacitySpecificationSummary) DeepCopyInto(out *CapacitySpecificationSummary) {
	*out = *in
	if in.LastUpdateToPayPerRequestTimestamp != nil {
		in, out := &in.LastUpdateToPayPerRequestTimestamp, &out.LastUpdateToPayPerRequestTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ReadCapacityUnits != nil {
		in, out := &in.ReadCapacityUnits, &out.ReadCapacityUnits
		*out = new(int64)
		**out = **in
	}
	if in.ThroughputMode != nil {
		in, out := &in.ThroughputMode, &out.ThroughputMode
		*out = new(string)
		**out = **in
	}
	if in.WriteCapacityUnits != nil {
		in, out := &in.WriteCapacityUnits, &out.WriteCapacityUnits
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacitySpecificationSummary.
func (in *CapacitySpecificationSummary) DeepCopy() *CapacitySpecificationSummary {
	if in == nil {
		return nil
	}
	out := new(CapacitySpecificationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSideTimestamps) DeepCopyInto(out *ClientSideTimestamps) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSideTimestamps.
func (in *ClientSideTimestamps) DeepCopy() *ClientSideTimestamps {
	if in == nil {
		return nil
	}
	out := new(ClientSideTimestamps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusteringKey) DeepCopyInto(out *ClusteringKey) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OrderBy != nil {
		in, out := &in.OrderBy, &out.OrderBy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusteringKey.
func (in *ClusteringKey) DeepCopy() *ClusteringKey {
	if in == nil {
		return nil
	}
	out := new(ClusteringKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnDefinition) DeepCopyInto(out *ColumnDefinition) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnDefinition.
func (in *ColumnDefinition) DeepCopy() *ColumnDefinition {
	if in == nil {
		return nil
	}
	out := new(ColumnDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Comment) DeepCopyInto(out *Comment) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Comment.
func (in *Comment) DeepCopy() *Comment {
	if in == nil {
		return nil
	}
	out := new(Comment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSpecification) DeepCopyInto(out *EncryptionSpecification) {
	*out = *in
	if in.KMSKeyIdentifier != nil {
		in, out := &in.KMSKeyIdentifier, &out.KMSKeyIdentifier
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSpecification.
func (in *EncryptionSpecification) DeepCopy() *EncryptionSpecification {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldDefinition) DeepCopyInto(out *FieldDefinition) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldDefinition.
func (in *FieldDefinition) DeepCopy() *FieldDefinition {
	if in == nil {
		return nil
	}
	out := new(FieldDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Keyspace) DeepCopyInto(out *Keyspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Keyspace.
func (in *Keyspace) DeepCopy() *Keyspace {
	if in == nil {
		return nil
	}
	out := new(Keyspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Keyspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyspaceList) DeepCopyInto(out *KeyspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Keyspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyspaceList.
func (in *KeyspaceList) DeepCopy() *KeyspaceList {
	if in == nil {
		return nil
	}
	out := new(KeyspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyspaceSpec) DeepCopyInto(out *KeyspaceSpec) {
	*out = *in
	if in.KeyspaceName != nil {
		in, out := &in.KeyspaceName, &out.KeyspaceName
		*out = new(string)
		**out = **in
	}
	if in.ReplicationSpecification != nil {
		in, out := &in.ReplicationSpecification, &out.ReplicationSpecification
		*out = new(ReplicationSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyspaceSpec.
func (in *KeyspaceSpec) DeepCopy() *KeyspaceSpec {
	if in == nil {
		return nil
	}
	out := new(KeyspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyspaceStatus) DeepCopyInto(out *KeyspaceStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyspaceStatus.
func (in *KeyspaceStatus) DeepCopy() *KeyspaceStatus {
	if in == nil {
		return nil
	}
	out := new(KeyspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyspaceSummary) DeepCopyInto(out *KeyspaceSummary) {
	*out = *in
	if in.KeyspaceName != nil {
		in, out := &in.KeyspaceName, &out.KeyspaceName
		*out = new(string)
		**out = **in
	}
	if in.ReplicationRegions != nil {
		in, out := &in.ReplicationRegions, &out.ReplicationRegions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReplicationStrategy != nil {
		in, out := &in.ReplicationStrategy, &out.ReplicationStrategy
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyspaceSummary.
func (in *KeyspaceSummary) DeepCopy() *KeyspaceSummary {
	if in == nil {
		return nil
	}
	out := new(KeyspaceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionKey) DeepCopyInto(out *PartitionKey) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionKey.
func (in *PartitionKey) DeepCopy() *PartitionKey {
	if in == nil {
		return nil
	}
	out := new(PartitionKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PointInTimeRecovery) DeepCopyInto(out *PointInTimeRecovery) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PointInTimeRecovery.
func (in *PointInTimeRecovery) DeepCopy() *PointInTimeRecovery {
	if in == nil {
		return nil
	}
	out := new(PointInTimeRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PointInTimeRecoverySummary) DeepCopyInto(out *PointInTimeRecoverySummary) {
	*out = *in
	if in.EarliestRestorableTimestamp != nil {
		in, out := &in.EarliestRestorableTimestamp, &out.EarliestRestorableTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PointInTimeRecoverySummary.
func (in *PointInTimeRecoverySummary) DeepCopy() *PointInTimeRecoverySummary {
	if in == nil {
		return nil
	}
	out := new(PointInTimeRecoverySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaAutoScalingSpecification) DeepCopyInto(out *ReplicaAutoScalingSpecification) {
	*out = *in
	if in.AutoScalingSpecification != nil {
		in, out := &in.AutoScalingSpecification, &out.AutoScalingSpecification
		*out = new(AutoScalingSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaAutoScalingSpecification.
func (in *ReplicaAutoScalingSpecification) DeepCopy() *ReplicaAutoScalingSpecification {
	if in == nil {
		return nil
	}
	out := new(ReplicaAutoScalingSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSpecification) DeepCopyInto(out *ReplicaSpecification) {
	*out = *in
	if in.ReadCapacityAutoScaling != nil {
		in, out := &in.ReadCapacityAutoScaling, &out.ReadCapacityAutoScaling
		*out = new(AutoScalingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadCapacityUnits != nil {
		in, out := &in.ReadCapacityUnits, &out.ReadCapacityUnits
		*out = new(int64)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSpecification.
func (in *ReplicaSpecification) DeepCopy() *ReplicaSpecification {
	if in == nil {
		return nil
	}
	out := new(ReplicaSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSpecificationSummary) DeepCopyInto(out *ReplicaSpecificationSummary) {
	*out = *in
	if in.CapacitySpecification != nil {
		in, out := &in.CapacitySpecification, &out.CapacitySpecification
		*out = new(CapacitySpecificationSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSpecificationSummary.
func (in *ReplicaSpecificationSummary) DeepCopy() *ReplicaSpecificationSummary {
	if in == nil {
		return nil
	}
	out := new(ReplicaSpecificationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationGroupStatus) DeepCopyInto(out *ReplicationGroupStatus) {
	*out = *in
	if in.KeyspaceStatus != nil {
		in, out := &in.KeyspaceStatus, &out.KeyspaceStatus
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.TablesReplicationProgress != nil {
		in, out := &in.TablesReplicationProgress, &out.TablesReplicationProgress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationGroupStatus.
func (in *ReplicationGroupStatus) DeepCopy() *ReplicationGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSpecification) DeepCopyInto(out *ReplicationSpecification) {
	*out = *in
	if in.RegionList != nil {
		in, out := &in.RegionList, &out.RegionList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReplicationStrategy != nil {
		in, out := &in.ReplicationStrategy, &out.ReplicationStrategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSpecification.
func (in *ReplicationSpecification) DeepCopy() *ReplicationSpecification {
	if in == nil {
		return nil
	}
	out := new(ReplicationSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaDefinition) DeepCopyInto(out *SchemaDefinition) {
	*out = *in
	if in.AllColumns != nil {
		in, out := &in.AllColumns, &out.AllColumns
		*out = make([]*ColumnDefinition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ColumnDefinition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ClusteringKeys != nil {
		in, out := &in.ClusteringKeys, &out.ClusteringKeys
		*out = make([]*ClusteringKey, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ClusteringKey)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PartitionKeys != nil {
		in, out := &in.PartitionKeys, &out.PartitionKeys
		*out = make([]*PartitionKey, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PartitionKey)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StaticColumns != nil {
		in, out := &in.StaticColumns, &out.StaticColumns
		*out = make([]*StaticColumn, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StaticColumn)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaDefinition.
func (in *SchemaDefinition) DeepCopy() *SchemaDefinition {
	if in == nil {
		return nil
	}
	out := new(SchemaDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticColumn) DeepCopyInto(out *StaticColumn) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticColumn.
func (in *StaticColumn) DeepCopy() *StaticColumn {
	if in == nil {
		return nil
	}
	out := new(StaticColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Table) DeepCopyInto(out *Table) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Table.
func (in *Table) DeepCopy() *Table {
	if in == nil {
		return nil
	}
	out := new(Table)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Table) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableList) DeepCopyInto(out *TableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Table, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableList.
func (in *TableList) DeepCopy() *TableList {
	if in == nil {
		return nil
	}
	out := new(TableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpec) DeepCopyInto(out *TableSpec) {
	*out = *in
	if in.CapacitySpecification != nil {
		in, out := &in.CapacitySpecification, &out.CapacitySpecification
		*out = new(CapacitySpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSideTimestamps != nil {
		in, out := &in.ClientSideTimestamps, &out.ClientSideTimestamps
		*out = new(ClientSideTimestamps)
		(*in).DeepCopyInto(*out)
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(Comment)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultTimeToLive != nil {
		in, out := &in.DefaultTimeToLive, &out.DefaultTimeToLive
		*out = new(int64)
		**out = **in
	}
	if in.EncryptionSpecification != nil {
		in, out := &in.EncryptionSpecification, &out.EncryptionSpecification
		*out = new(EncryptionSpecification)
		(*in).DeepCopyInto(*out)
	}
	if in.KeyspaceName != nil {
		in, out := &in.KeyspaceName, &out.KeyspaceName
		*out = new(string)
		**out = **in
	}
	if in.PointInTimeRecovery != nil {
		in, out := &in.PointInTimeRecovery, &out.PointInTimeRecovery
		*out = new(PointInTimeRecovery)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaDefinition != nil {
		in, out := &in.SchemaDefinition, &out.SchemaDefinition
		*out = new(SchemaDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.TableName != nil {
		in, out := &in.TableName, &out.TableName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(TimeToLive)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpec.
func (in *TableSpec) DeepCopy() *TableSpec {
	if in == nil {
		return nil
	}
	out := new(TableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableStatus) DeepCopyInto(out *TableStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableStatus.
func (in *TableStatus) DeepCopy() *TableStatus {
	if in == nil {
		return nil
	}
	out := new(TableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSummary) DeepCopyInto(out *TableSummary) {
	*out = *in
	if in.KeyspaceName != nil {
		in, out := &in.KeyspaceName, &out.KeyspaceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.TableName != nil {
		in, out := &in.TableName, &out.TableName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSummary.
func (in *TableSummary) DeepCopy() *TableSummary {
	if in == nil {
		return nil
	}
	out := new(TableSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetTrackingScalingPolicyConfiguration) DeepCopyInto(out *TargetTrackingScalingPolicyConfiguration) {
	*out = *in
	if in.DisableScaleIn != nil {
		in, out := &in.DisableScaleIn, &out.DisableScaleIn
		*out = new(bool)
		**out = **in
	}
	if in.ScaleInCooldown != nil {
		in, out := &in.ScaleInCooldown, &out.ScaleInCooldown
		*out = new(int64)
		**out = **in
	}
	if in.ScaleOutCooldown != nil {
		in, out := &in.ScaleOutCooldown, &out.ScaleOutCooldown
		*out = new(int64)
		**out = **in
	}
	if in.TargetValue != nil {
		in, out := &in.TargetValue, &out.TargetValue
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetTrackingScalingPolicyConfiguration.
func (in *TargetTrackingScalingPolicyConfiguration) DeepCopy() *TargetTrackingScalingPolicyConfiguration {
	if in == nil {
		return nil
	}
	out := new(TargetTrackingScalingPolicyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeToLive) DeepCopyInto(out *TimeToLive) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeToLive.
func (in *TimeToLive) DeepCopy() *TimeToLive {
	if in == nil {
		return nil
	}
	out := new(TimeToLive)
	in.DeepCopyInto(out)
	return out
}
